In [ ]:
import numpy as np
arr_1 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/testmarks1.csv',delimiter=',',dtype=str,skiprows=1)
arr_2 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/testmarks2.csv',delimiter=',',dtype=str,skiprows=1)
print(arr_1)
print(arr_2)


[['801' '43.05' '27.79' '28.7' '27.79']
 ['802' '43.47' '28.52' '28.98' '27.89']
 ['803' '42.24' '28.16' '28.16' '25.63']
 ['804' '39.24' '26.16' '26.16' '26.16']
 ['805' '40.9' '26.03' '27.27' '25.65']
 ['806' '39.47' '26.31' '26.31' '25.21']
 ['807' '41.68' '25.63' '27.79' '25.46']
 ['808' '42.19' '27.61' '28.13' '26.21']
 ['809' '44.75' '28.35' '29.83' '28.21']
 ['810' '46.95' '28.88' '31.3' '28.53']]
[['801' '28.48' '34.18' '30.56' '22.23']
 ['802' '28.1' '33.72' '30.68' '22.82']
 ['803' '26.16' '31.39' '28.2' '22.53']
 ['804' '26.16' '31.39' '28.78' '20.93']
 ['805' '26.1' '31.32' '28.22' '20.82']
 ['806' '25.45' '30.54' '27.73' '21.05']
 ['807' '26.16' '31.39' '28.01' '20.51']
 ['808' '27.44' '32.93' '28.83' '22.08']
 ['809' '28.63' '34.35' '31.03' '22.68']
 ['810' '30.35' '36.42' '31.38' '23.1']]


In [ ]:
import numpy as np
arr_1 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/testmarks1.csv',delimiter=',',dtype=str,skiprows=1)
arr_2 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/testmarks2.csv',delimiter=',',dtype=str,skiprows=1)
print(arr_1)
print(arr_2)
SIC=[]
EDS=[]
EEE=[]
PHY=[]
EGR=[]
for i in arr_1:
  SIC.append(int(i[1]))
  EDS.append(int(i[2]))
  EEE.append(int(i[3]))
  PHY.append(int(i[4]))
  EGR.append(int(i[5]))

print(SIC)
print(EDS)
print(EEE)
print(PHY)
print(EGR)

#CONVERTING LIST TO ARRAY
arr_SIC = np.array(SIC)
arr_EDS = np.array(EDS)
arr_EEE = np.array(EEE)
arr_PHY = np.array(PHY)
arr_EGR = np.array(EGR)

#DISPLAYING ARRAY
print("Array1: ",arr_SIC)
print("Array2: ",arr_EDS)
print("Array3: ",arr_EEE)
print("Array4: ",arr_PHY)
print("Array5: ",arr_EGR)

arr_SIC.shape










[['801' '43.05' '27.79' '28.7' '27.79']
 ['802' '43.47' '28.52' '28.98' '27.89']
 ['803' '42.24' '28.16' '28.16' '25.63']
 ['804' '39.24' '26.16' '26.16' '26.16']
 ['805' '40.9' '26.03' '27.27' '25.65']
 ['806' '39.47' '26.31' '26.31' '25.21']
 ['807' '41.68' '25.63' '27.79' '25.46']
 ['808' '42.19' '27.61' '28.13' '26.21']
 ['809' '44.75' '28.35' '29.83' '28.21']
 ['810' '46.95' '28.88' '31.3' '28.53']]
[['801' '28.48' '34.18' '30.56' '22.23']
 ['802' '28.1' '33.72' '30.68' '22.82']
 ['803' '26.16' '31.39' '28.2' '22.53']
 ['804' '26.16' '31.39' '28.78' '20.93']
 ['805' '26.1' '31.32' '28.22' '20.82']
 ['806' '25.45' '30.54' '27.73' '21.05']
 ['807' '26.16' '31.39' '28.01' '20.51']
 ['808' '27.44' '32.93' '28.83' '22.08']
 ['809' '28.63' '34.35' '31.03' '22.68']
 ['810' '30.35' '36.42' '31.38' '23.1']]


ValueError: ignored

In [ ]:
#Arithmetic operation
#1.Addition operation
resultarray=np.add(arr_SIC,arr_EDS)
print(resultarray)


[147 148 156 169 146 172 136 126 126 147]


In [ ]:
#2.Subtraction operation
resultarray=np.subtract(arr_SIC,arr_EDS)
print(resultarray)

[  9 -10  -2  -9 -10  16   2 -10 -10 -11]


In [ ]:
#3.Multiplication operation
resultarray=np.multiply(arr_SIC,arr_EDS)
print(resultarray)

[5382 5451 6083 7120 5304 7332 4623 3944 3944 5372]


In [ ]:
#4.Divison operation
resultarray=np.divide(arr_SIC,arr_EDS)
print(resultarray)

[1.13043478 0.87341772 0.97468354 0.8988764  0.87179487 1.20512821
 1.02985075 0.85294118 0.85294118 0.86075949]


In [ ]:
#5.Mod
resultarray=np.mod(arr_SIC,arr_EDS)
print(resultarray)

[ 9 69 77 80 68 16  2 58 58 68]


In [ ]:
#6.Dot Product
resultarray=np.dot(arr_SIC,arr_EDS)
print(resultarray)

54555


In [ ]:
#7.Transpose
resultarray=np.transpose(arr_SIC)
print(resultarray)

[78 69 77 80 68 94 69 58 58 68]


2.Statistical Operations

In [ ]:
#1.mean
resultarray=np.mean(arr_SIC)
print(resultarray)

71.9


In [ ]:
#2.Median
resultarray=np.median(arr_SIC)
print(resultarray)

69.0


In [ ]:
#3.Average
resultarray=np.average(arr_SIC)
print(resultarray)

In [ ]:
#4.VARIANCE
resultarray=np.var(arr_SIC)
print(resultarray)

105.09


In [ ]:
#5.STANDARD DEVIATION
resultarray=np.std(arr_SIC)
print(resultarray)

10.251341375644458


In [ ]:
#6.MAximum value
resultarray=np.amax(arr_SIC)
print(resultarray)

94


In [ ]:
#7.MINIMUM VALUE
resultarray=np.amin(arr_SIC)
print(resultarray)

58


SORTING

In [ ]:
arr_1 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/FirstDecade.csv',delimiter=',',dtype=str,skiprows=1)
arr_2 = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/SecondDecade.csv',delimiter=',',dtype=str,skiprows=1)

array1=np.sort(arr_1,axis=0)#Horizontally Sort
print(array1)

array1=np.sort(arr_1,axis=1)#Vertically Sort
print(array1)


[['0' '0' '2002-08-12' ... '0' '0' '0']
 ['1' '1' '2002-08-13' ... '0' '0' '0']
 ['10' '10' '2002-08-14' ... '0' '0' '0']
 ...
 ['997' '997' '2010-12-28' ... '9986220' '1.25' '0']
 ['998' '998' '2010-12-29' ... '9997992' '1.25' '2']
 ['999' '999' '2010-12-30' ... '9998480' '5' '2']]
[['0' '0' '0' ... '27.78542288' '28.48499298' '28.70024427']
 ['0' '0' '1' ... '28.09933281' '28.52086876' '28.97827946']
 ['0' '0' '2' ... '28.16211253' '28.16211253' '822776']
 ...
 ['0' '0' '1012876' ... '448.7846543' '450.8099365' '452.5992742']
 ['0' '0' '1042370' ... '451.8522033' '454.9785767' '456.9645433']
 ['0' '0' '2010-12-30' ... '453.2285209' '460.1891479' '461.9981679']]


Data stacking

In [ ]:
array1=np.array(np.arange(1,5).reshape(2,2))
print(array1)
array2=np.array(np.arange(11,15).reshape(2,2))
print(array1)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Horizontal Stacking

In [ ]:
resultarray=np.hstack((arr_SIC,arr_EDS))
print(resultarray)

[78 69 77 80 68 94 69 58 58 68 69 79 79 89 78 78 67 68 68 79]


Vertical Stacking

In [ ]:
resultarray=np.hstack((arr_SIC,arr_EDS))
print(resultarray)

[78 69 77 80 68 94 69 58 58 68 69 79 79 89 78 78 67 68 68 79]


Append

In [ ]:
array1=np.arange(1,10).reshape(3,3)
print(arr_1)
array2=np.arange(1,10).reshape(3,3)
print(arr_2)

[['801' '43.05' '27.79' '28.7' '27.79']
 ['802' '43.47' '28.52' '28.98' '27.89']
 ['803' '42.24' '28.16' '28.16' '25.63']
 ['804' '39.24' '26.16' '26.16' '26.16']
 ['805' '40.9' '26.03' '27.27' '25.65']
 ['806' '39.47' '26.31' '26.31' '25.21']
 ['807' '41.68' '25.63' '27.79' '25.46']
 ['808' '42.19' '27.61' '28.13' '26.21']
 ['809' '44.75' '28.35' '29.83' '28.21']
 ['810' '46.95' '28.88' '31.3' '28.53']]
[['801' '28.48' '34.18' '30.56' '22.23']
 ['802' '28.1' '33.72' '30.68' '22.82']
 ['803' '26.16' '31.39' '28.2' '22.53']
 ['804' '26.16' '31.39' '28.78' '20.93']
 ['805' '26.1' '31.32' '28.22' '20.82']
 ['806' '25.45' '30.54' '27.73' '21.05']
 ['807' '26.16' '31.39' '28.01' '20.51']
 ['808' '27.44' '32.93' '28.83' '22.08']
 ['809' '28.63' '34.35' '31.03' '22.68']
 ['810' '30.35' '36.42' '31.38' '23.1']]
